### ISSUE TITLE
class name minor issue

### ISSUE THREAD

**Issue by farishkash** [WennDann/prj-rev-bwfs-tea-cozy#1]
This is more of a thought process, code overall is excellent.

So we have a couple classes here:

```
 <div class="top3">

<div class="top4and5">

```
These class names aren't really meaningful.  Yes you are conveying the number but even that isn't clear unless you are looking at the website.

As an example featuredteas-top-row fits the description of the items better.

Also it is ok to have classes with the same name as ids as they are consider to be two different items.

Example here

```
<div id="locations">
        <h2>Locations</h2>
        <div class="areas">
          <div class="area">

```
could be written as

```
<div id="locations">
        <h2>Locations</h2>
        <div class="locations">
          <div class="location">

```

Now you can choose whatever you like I am just trying to convey some ideas here.

**Comment by WennDann** [comment]
Thank you @farishkash . This is very much appreciated. I didn't know it was allowed to have classes and ids of same name. I'll try to play around and see what suits me better.
And regarding the names, you got a very important point there, which I will try to adopt in future code. It is really not meaningful to someone not seeing the webpage, what I meant with these classes. Thank you.
