### ISSUE TITLE
css a little repetitive

### ISSUE THREAD

**Issue by farishkash** [WennDann/prj-rev-bwfs-tea-cozy#2]
A couple examples here

You use

```
display: flex;
flex-direction: column;

display: flex;
flex-flow: column;  <---without using the wrap this is the same as flex  direction

```
repeatedly.

It would be better if you made a class that did this and just apply the class to each div
then use the other class to apply custom css.

```
.flexcolumn {
display: flex;
flex-direction: column;
}

```

now your mission css becomes

```
#mission {
  background-image: url('../images/img-mission-background.jpg');
  height: 700px;
  width: 1200px;
  justify-content: center;
  padding-top: 70px;
}

```

And then we change this div

from

`<div id="mission">`

to 

`<div id="mission" class="flexcolumn">`

If I counted correctly this removes about 20 lines off your css page.

**Comment by WennDann** [comment]
@farishkash Thank you very much for this insight as well. I didn't even think I could do that, but it bothered me, too. Each and every time adding the same code doesn't make any sense and is not handy to read. I definitely adopt this in my next projects.
